graph TD
  u0["min_token.py"]
  u1["pirgen.py"]
  u2["analyzers/c_analyzer.py"]
  u3["analyzers/rust_analyzer.py"]
  u4["analyzers/java_analyzer.py"]
  u5["analyzers/base.py"]
  u6["analyzers/asm_ld_analyzer.py"]
  u7["analyzers/__init__.py"]
  u8["analyzers/python_analyzer.py"]
  u9["core/profile_canon.py"]
  u10["core/analysis_cache.py"]
  u11["core/project_model.py"]
  u12["core/pir_builder.py"]
  u13["core/dep_canon.py"]

  ext:stdlib_py["stdlib:py"]
  u0 -->|refs| ext:stdlib_py
  u1 -->|refs| ext:stdlib_py
  ext:core.project_model["core.project_model"]
  u1 -->|refs| ext:core.project_model
  ext:core.pir_builder["core.pir_builder"]
  u1 -->|refs| ext:core.pir_builder
  ext:core.dep_canon["core.dep_canon"]
  u1 -->|refs| ext:core.dep_canon
  ext:core.profile_canon["core.profile_canon"]
  u1 -->|refs| ext:core.profile_canon
  ext:core.analysis_cache["core.analysis_cache"]
  u1 -->|refs| ext:core.analysis_cache
  ext:analyzers["analyzers"]
  u1 -->|refs| ext:analyzers
  u2 -->|refs| ext:stdlib_py
  ext:.base[".base"]
  u2 -->|refs| ext:.base
  u2 -->|refs| ext:core.project_model
  u3 -->|refs| ext:stdlib_py
  u3 -->|refs| ext:.base
  u3 -->|refs| ext:core.project_model
  u4 -->|refs| ext:stdlib_py
  u4 -->|refs| ext:.base
  u4 -->|refs| ext:core.project_model
  u5 -->|refs| ext:stdlib_py
  u5 -->|refs| ext:core.project_model
  u6 -->|refs| ext:stdlib_py
  u6 -->|refs| ext:.base
  u6 -->|refs| ext:core.project_model
  ext:.c_analyzer[".c_analyzer"]
  u7 -->|refs| ext:.c_analyzer
  ext:.python_analyzer[".python_analyzer"]
  u7 -->|refs| ext:.python_analyzer
  ext:.java_analyzer[".java_analyzer"]
  u7 -->|refs| ext:.java_analyzer
  ext:.rust_analyzer[".rust_analyzer"]
  u7 -->|refs| ext:.rust_analyzer
  ext:.asm_ld_analyzer[".asm_ld_analyzer"]
  u7 -->|refs| ext:.asm_ld_analyzer
  u8 -->|refs| ext:stdlib_py
  u8 -->|refs| ext:.base
  u8 -->|refs| ext:core.project_model
  u9 -->|refs| ext:stdlib_py
  u10 -->|refs| ext:stdlib_py
  u11 -->|refs| ext:stdlib_py
  ext:.project_model[".project_model"]
  u12 -->|refs| ext:.project_model